### ISSUE TITLE
Panic when the last header is empty

### ISSUE THREAD

**Issue by mernen** [aeshirey/EmlParser#11]
Evaluating the following panics:

```rust
EmlParser::from_string("Foo: ok\nBar: \n\nHello".to_string())
        .ignore_body()
        .parse()
```

Stack trace:

```
thread 'main' panicked at 'begin <= end (13 <= 12) when slicing `Foo: ok
Bar: 

Hello`', .../eml-parser-0.1.0/src/parser.rs:390:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::str::slice_error_fail
   3: core::str::traits::<impl core::slice::index::SliceIndex<str> for core::ops::range::Range<usize>>::index
             at .../rustlib/src/rust/library/core/src/str/traits.rs:214:21
   4: core::str::traits::<impl core::ops::index::Index<I> for str>::index
             at .../rustlib/src/rust/library/core/src/str/traits.rs:64:9
   5: <alloc::string::String as core::ops::index::Index<core::ops::range::Range<usize>>>::index
             at .../rustlib/src/rust/library/alloc/src/string.rs:2033:10
   6: eml_parser::parser::EmlParser::read_field_body
             at .../eml-parser-0.1.0/src/parser.rs:390:14
   7: eml_parser::parser::EmlParser::read_raw_header_field
             at .../eml-parser-0.1.0/src/parser.rs:234:25
   8: eml_parser::parser::EmlParser::parse_header_field
             at .../eml-parser-0.1.0/src/parser.rs:127:41
   9: eml_parser::parser::EmlParser::parse_email
             at .../eml-parser-0.1.0/src/parser.rs:99:23
  10: eml_parser::parser::EmlParser::parse
             at .../eml-parser-0.1.0/src/parser.rs:90:19
  11: eml_parser_bug::main
             at ./src/main.rs:6:17
```

Swapping headers (making the last one non-empty) works fine.

**Comment by mernen** [comment]
Looking more into it, it seems like the last character of the last header is always bitten off. For example, in the `TEST_HEADER` used in tests, the last header `foo: bar` yields `HeaderFieldValue::Unstructured("ba")`.

I'm not sure how to fix it, as I'd need to be more familiar with the state machine to make sure I'm not breaking something else...

**Comment by aeshirey** [comment]
#12

**Comment by aeshirey** [comment]
The issue here was when [`read_field_body` returns](https://github.com/aeshirey/EmlParser/blob/c00ef1076739d15a76dd965fee2bb907d623d91d/src/parser.rs#L390) and `start_position == end_position`. I now [check for this](https://github.com/aeshirey/EmlParser/blob/58ac4e92cfd58c34fe31aefb50ce804df673d066/src/parser.rs#L389) and return the empty string as appropriate.

I also incorporated [your test example](https://github.com/aeshirey/EmlParser/blob/58ac4e92cfd58c34fe31aefb50ce804df673d066/src/parser.rs#L588), which passes.

**Comment by mernen** [comment]
That was the original fix I was going to propose, but then I realized the issue [in my comment](https://github.com/aeshirey/EmlParser/issues/11#issuecomment-778799419). I think there's a deeper issue here when handling the last header, and the empty case was just more pronounced due to the crash.

**Comment by aeshirey** [comment]
Adding in the `LwspState::EndOfHeader_*` variants lets `read_field_body` identify when it's at the end of a single header value vs the entire header and can thus handle this issue. It also handles what `remove_header_body_separator` was doing.

All tests pass, and [a new test](https://github.com/aeshirey/EmlParser/blob/60c701cc5d26af25476edb1c70d78f49e20aa77d/src/parser.rs#L649) checks for this last header value:

```rust
let eml: Eml = EmlParser::from_string("Foo: ok\nBar: super\n\nHello".to_string())
	.with_body()
	.parse()
	.unwrap();
// ...
let bar = &eml.headers[1];
let HeaderField { name, value } = bar;
assert_eq!("Bar", name);
assert_eq!(&HeaderFieldValue::Unstructured("super".to_string()), value);
```

**Comment by aeshirey** [comment]
[`eml-parser = "0.1.2"`](https://crates.io/crates/eml-parser) is now available on crates.io. Thanks for pointing out the issue, @mernen !
