### ISSUE TITLE
Use either EmlError::IoError or io::Error

### ISSUE THREAD

**Issue by robinkrahl** [aeshirey/EmlParser#6]
The `EmlError` enum has an `IoError` variant that does not store the root `io::Error` and that is never instantiated (AFAIS).  The `EmlParser::from_file` function returns an `io::Error` instead.  It would be clearer if you (1) either use `EmlError::IoError` instead of `io::Error` or (2) remove the `IoError` variant.  In case (1), it would make sense to store the `io::Error` to add some context to the error.

**Comment by aeshirey** [comment]
Good idea. I wrote EmlParser as basically my first crate, so it's probably lacking in Rust idioms.

**Comment by aeshirey** [comment]
PR #8 improves this, though I didn't add any context to the error.

**Comment by robinkrahl** [comment]
Thanks!
